language: node_js
node_js: stable
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - DB_PORT=5432
    - DB_DATABASE=teamwork_test
    - DB_USER=postgres
before_script:
  - psql -c "CREATE DATABASE teamwork_test;" -U postgres  
install:
  - npm install
script:
  - npm test
