language: node_js
node_js: stable
services:
- postgresql
addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
deploy:
  provider: heroku
  api_key:
    secure: u3HQ0Ey79zGcKmn242VhyxPazNum46M3QfSkg6ZTBtGyw7lftg+7qhc8iJ0P75D0yu1G57vvkhVNg7xbzPSdqso2NKFWwliRf0TkOMrMGCO2tremuHYmqVAIRjBR9VXXaBsovRQV05MY5JRz2BCsP2AzobvPVD3tl1pJTb7I1hqRKAmSUo3CzVHfPPh5oOoqjfm8gw0wngfn7sx7J7cZuLlzKhTyNbecgJk3vvJYnkmt0U2KPpK377JO6h/AS8UZlniGyHu0HPGQLnTbeP8W9Em0AhEuXgfCVj6YlJdV+mFl0wvM5oIDCF33cIiOB0bCzgc7gEhFpMrdiBI+gfHW+yCY0dzO+BCP/iWNeylW0q82GjS5YEqWLb8RiOEqnszcYjdEjapZ9tIy1K9Gn1R+vviN7XynswP2d0mjfAGRXahLjZXvfRMAmKqdxtKAf8xRz0feHwNO/P5iXYO5KG2KJVZJRnevrxBnZH7MoagbxCxvtZ8OtY7vbYm1ZyymJ/59S1ZNb/fUaxqWcFx6SR+2zqPQ3R3CpDHZixLrvv05/DWW+lciS8WRhQIj2831IbRZldUV/Littag1vVvS78cQ/gs0BcSMVa43j9cFZwIn9N4njkDvVOb7wLVEIk1uGJGvtncjg7i0NAEpsy0a76kJ09h54xSWkHdfkLYiYIVe278=
  skip_cleanup: true
install:
- npm install
script:
- npm test
env:
  global:
    secure: mW/B+Z6YaMiNw8ri8DUE4SUOuqwWPntGK3c99FlrnGaCqpNQiTjv00p83+ER2BvuC2/X86f61VsBnxxptLBeiyGTmufWVEKlqbNg/TZokYuECu5BL0hlPybbTjRyYev2qnU0quIGLtiymQpA6oX3TAF5lqZ03VNUYCAJoC3A2H1WU/JgmmEcRR/mratZ0ZIFvbmoezVD/tRQir4/NK9+iS7gAU4LRLZen9HyubE2IpSNDV1g4XHpX2mTEbP5hRuiIywUd303SLKFRGkAyGu3RgZ5Wk8llC+W2VAhmjaWdT9uKMTYwz+v7yJlQsDQSvCbjt01ljouGBWm7vOyR3n8CCwH1BPajBCRvnwAMRQ6H/HhZA6IRakcKL6SpdQ1CH08GCZITwi12/iLi6bxZgAcsmZ1AfONLevauhyoS/rIw1EeiTvXwwtcPuO2fAUm97KdMkhY/FjDvPYMhgh/W7+2KkPm9JAWh6KBUwFdKDil5Z5CwOdDMnHzODi/C79+M80XJOaCVc8vxoXTlw1u+YYyx3HfuIDoy0ZzGIoQ80u4R8slez3gJnSaGM0Yi3eOBSwcy2JVi4Qf3EMktT0qPZOaP+lr+0/hzTvTzKduGWSYrGxz4dWm2vc5U9sdkO9AubBgx74pnf6OsRmydpYV6tCf94fVE7UplX/XD+UTRn/dSrY=
