language: node_js
node_js: stable
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - DB_PORT=5432
    - DB_DATABASE=teamwork_test
    - DB_USER=postgres
    - DB_HOST=127.0.0.1
    - JWT_SECRET=thistokenformyapp
    - CLOUDINARY_API_SECRET=GNdbF3gFI20HhfrcqjZhWrWxxZI
    - CLOUDINARY_API_KEY=342421579684833
    - CLOUDINARY_CLOUD_NAME=dhclgjajx
before_script:
  - createdb -T template0 teamwork_test 
  - psql --set ON_ERROR_STOP=on -U postgres teamwork_test < -f ./db/database.sql
install:
  - npm install
script:
  - npm test
