language: node_js
node_js: stable
services:
- postgresql
addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
deploy:
  provider: heroku
  api_key:
    secure: KZUWqgDraY38pWvO5HOUgd2DELIU1ZJhnQRTY+lISZlJPRf8zmzR72AqpJG3Rv2N1IGJwGCzxabiBTJ7g/KewVin1YrtuaAWc9+s0vsYKPv8rWk4y6UIvzh50eQXKj8tIbCCYI+V4XErFA7ISRuvH0umgwA1AazdeUSk78ch32xAmTCDodVOJFQmoYMceNY6GJXC3qmlbsDa/4algqQFFOUlN+jQjuBf/pbw0Xsde+7d4KO1CIiwGuPK0IDIVUEy0HmctlcsBBkRJlOFtJVisMar8/uaww7T1R/c0HIJ15IDAHMa06Ixo7K9TIjBqCvhrliqCI9n02H1k9Gbx3CaB23eoblp5SmZcQLvHmk8MMqybJneFbQaHKAWSXIkTNiueJlMSFDgv2yGLhB7DJI6DAYPqxtF/XSapcwYO+iCFm88+JFM+pMz2mmaZPfC83FXR8G9ozfSGCkaS+Xbys9PqWQwQmApHeOfzTv6fMqLRSF0KnMW+lclhRun7nZBFIZwCAxKqsi2RBjULmmE0g7uuTnMaY5B8/MVFxk7J+B1itwibhc0EORShrTYh0m7aG0+EI6B7Q5cGCLwJigTz92F7/b6r+ZfYUYXCngcBumlrP2nTFFXkGmeIZb+otLtuNNAzRMqRmbEgYSy/T3wmQphRsbNs/Kg/yMRy2rmvYf+s30=
  skip_cleanup: true
install:
- npm install
script:
- npm test
env:
  global:
    secure: mW/B+Z6YaMiNw8ri8DUE4SUOuqwWPntGK3c99FlrnGaCqpNQiTjv00p83+ER2BvuC2/X86f61VsBnxxptLBeiyGTmufWVEKlqbNg/TZokYuECu5BL0hlPybbTjRyYev2qnU0quIGLtiymQpA6oX3TAF5lqZ03VNUYCAJoC3A2H1WU/JgmmEcRR/mratZ0ZIFvbmoezVD/tRQir4/NK9+iS7gAU4LRLZen9HyubE2IpSNDV1g4XHpX2mTEbP5hRuiIywUd303SLKFRGkAyGu3RgZ5Wk8llC+W2VAhmjaWdT9uKMTYwz+v7yJlQsDQSvCbjt01ljouGBWm7vOyR3n8CCwH1BPajBCRvnwAMRQ6H/HhZA6IRakcKL6SpdQ1CH08GCZITwi12/iLi6bxZgAcsmZ1AfONLevauhyoS/rIw1EeiTvXwwtcPuO2fAUm97KdMkhY/FjDvPYMhgh/W7+2KkPm9JAWh6KBUwFdKDil5Z5CwOdDMnHzODi/C79+M80XJOaCVc8vxoXTlw1u+YYyx3HfuIDoy0ZzGIoQ80u4R8slez3gJnSaGM0Yi3eOBSwcy2JVi4Qf3EMktT0qPZOaP+lr+0/hzTvTzKduGWSYrGxz4dWm2vc5U9sdkO9AubBgx74pnf6OsRmydpYV6tCf94fVE7UplX/XD+UTRn/dSrY=
