language: node_js
node_js: stable
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  - ELEPHANTDB_DATABASE="ozmkltfh"
install:
  - npm install
cache:
  directories:
    - "$HOME/.npm"
script:
  - npm test
