language: node_js
node_js: stable
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - ELEPHANTDB_USER=$ELEPHANTDB_USER
    - ELEPHANTDB_PASS=$ELEPHANTDB_PASS
    - ELEPHANTDB_HOST=$ELEPHANTDB_HOST
    - ELEPHANTDB_PORT=$ELEPHANTDB_PORT
    - ELEPHANTDB_DATABASE=ozmkltfh
install:
  - npm install
script:
  - npm test
