language: node_js
node_js: stable
services:
- postgresql
addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
deploy:
  provider: heroku
  api_key:
    secure: Vw1MBSVXf0PnWyiHHL6XHVZhM1u66V7miD+qd9C+LRUFQWwio+fNm/01NPzFP2ctr9LnPZ81EovleSzeye2Lk+SDSZSsP5TZMXxBKPwX/w6vWAsKEZGw6PJuizzUg1pomX13fSYUiSic19FcI4RnCBiumcvXD0aIy/JP7FvtT/RcIcpevAdioLHUxWceUzJtjt2pLOIU1f4GvWsJXbZTehjleNWkwoyzULqOU//SoADnJ7PM6K+jTxi2AHOPf7AhzBsoSBhDY04j618X78+y3TZtSMkDeHfhB5CwJ+ETaM2u3QpSqX2eH7+XH3iBdZtjXy+dno+eyXc9SUXQRyGYzQ7Gig68shPGmS1ica6Odf4JBm7a/SDJjlsOOccCxmk7M1LYrYN7x96m5cQIFlsN686NDDGscTg3agP2wbTNPbMJwbFwCb7W/qjqHR3pDiPWWzTYV1J75YSJQJSLb6jh7FX4iv6uI/UlUf6uBfNHa7RiLNwxOFWw3C2rUFK0lnx3v7yUeiO0OmiuynoVd4q5hE0P/eJ4uEkCA2yerfifdDETYVYj22kAFtjHe0uiYu6BXotsbU/7+2sTZBaAyJRw/cYW6Ijan32QaQT1RrzX6Vs1NLaL+tZiW2avqH7x0mmeAhYd5e4ydk8t6oEhS7wur9WTQEPnzWrCRGappHqs3LI=
  skip_cleanup: true
install:
- npm install
script:
- npm test
env:
  global:
    secure: mW/B+Z6YaMiNw8ri8DUE4SUOuqwWPntGK3c99FlrnGaCqpNQiTjv00p83+ER2BvuC2/X86f61VsBnxxptLBeiyGTmufWVEKlqbNg/TZokYuECu5BL0hlPybbTjRyYev2qnU0quIGLtiymQpA6oX3TAF5lqZ03VNUYCAJoC3A2H1WU/JgmmEcRR/mratZ0ZIFvbmoezVD/tRQir4/NK9+iS7gAU4LRLZen9HyubE2IpSNDV1g4XHpX2mTEbP5hRuiIywUd303SLKFRGkAyGu3RgZ5Wk8llC+W2VAhmjaWdT9uKMTYwz+v7yJlQsDQSvCbjt01ljouGBWm7vOyR3n8CCwH1BPajBCRvnwAMRQ6H/HhZA6IRakcKL6SpdQ1CH08GCZITwi12/iLi6bxZgAcsmZ1AfONLevauhyoS/rIw1EeiTvXwwtcPuO2fAUm97KdMkhY/FjDvPYMhgh/W7+2KkPm9JAWh6KBUwFdKDil5Z5CwOdDMnHzODi/C79+M80XJOaCVc8vxoXTlw1u+YYyx3HfuIDoy0ZzGIoQ80u4R8slez3gJnSaGM0Yi3eOBSwcy2JVi4Qf3EMktT0qPZOaP+lr+0/hzTvTzKduGWSYrGxz4dWm2vc5U9sdkO9AubBgx74pnf6OsRmydpYV6tCf94fVE7UplX/XD+UTRn/dSrY=
