language: node_js
node_js: stable
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  globals:
    - CLOUDINARY_API_SECRET=$CLOUDINARY_API_SECRET
    - CLOUDINARY_API_KEY=$CLOUDINARY_API_KEY
    - CLOUDINARY_CLOUD_NAME=$CLOUDINARY_CLOUD_NAME
    - ELEPHANTDB_USER=$ELEPHANTDB_USER
    - ELEPHANTDB_PASS=$ELEPHANTDB_PASS
    - ELEPHANTDB_HOST=$ELEPHANTDB_HOST
    - ELEPHANTDB_PORT=$ELEPHANTDB_PORT
    - ELEPHANTDB_DATABASE=$ELEPHANTDB_DATABASE
install:
  - npm install
script:
  - npm test
