language: node_js
node_js: stable
sudo: false
install:
  - npm install
script:
  - npm prod
  env:
  global:
   - JWT_SECRET=thistokenformyapp
   - CLOUDINARY_API_SECRET=GNdbF3gFI20HhfrcqjZhWrWxxZI
   - CLOUDINARY_API_KEY=342421579684833
   - CLOUDINARY_CLOUD_NAME=dhclgjajx